version: "3.7"

services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node.dockerfile
      args:
        NPM_USER: dunloop
        NPM_TOKEN: 9ba96cfa9db6def87a11cfd2f048a7629154baf9
        NPM_EMAIL: dunloop8@gmail.com
        NPM_REGISTRY: https://npm.pkg.github.com
        NPM_SCOPE: "@jfxteam"
    command: "npm run start"
    ports:
      - "$APP_HOST:$APP_PORT:80"
      - "9229:9229"
    environment:
      NODE_ENV: $NODE_ENV
      APP_HOST: 0.0.0.0
      APP_PORT: 80
      APP_DEV_INSPECT: $APP_DEV_INSPECT
      APP_DEV_INSPECT_BRK: $APP_DEV_INSPECT_BRK