version: "3.7"

services:
  web:
    build:
      context: ./
      args:
        NODE_ENV: $NODE_ENV
        #NPM_USER: $NPM_USER
        #NPM_TOKEN: $NPM_TOKEN
        #NPM_EMAIL: $NPM_EMAIL
        #NPM_REGISTRY: $NPM_REGISTRY
        #NPM_SCOPE: $NPM_SCOPE
    command: "npm start"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html/src
    ports:
      - "$APP_HOST:$APP_PORT:80"
      - "9229:9229"
    environment:
      NODE_ENV: $NODE_ENV
      APP_HOST: 0.0.0.0
      APP_PORT: 80
      APP_DEV_INSPECT: $APP_DEV_INSPECT
      APP_DEV_INSPECT_BRK: $APP_DEV_INSPECT_BRK
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "$DB_HOST:$DB_PORT:5432"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD

volumes:
  postgresql-data:
